### ISSUE TITLE
 edited your manifest.json to get rid of errors, here's the code.

### ISSUE THREAD

**Issue by Kronosthelad** [lure0xaos/TwineHacker#3]
`{
  "name": "TwineHacker",
  "version": "2.1.0",
  "description": "Allows you to change font/style; also adds cheats",
  "manifest_version": 3,
  "permissions": [
    "activeTab",
    "tabs",
    "storage"
  ],
  "host_permissions": [
    "file://*/*",
    "file://*/",
    "https://*/",
    "https://*/*/"
  ],
  "icons": {
    "16": "icons/16.png",
    "48": "icons/48.png",
    "128": "icons/128.png"
  },
  "devtools_page": "devtools.html",
  "options_page": "options.html"
}`

**Comment by lure0xaos** [comment]
thank you!
